//array methods in java script

// d=[34,564,5,44,4,2,343]
// d.sort();
// console.log(d.length);
// console.log(d.pop());
//  console.log(d.push("rishi"));
// console.log(d.shift());
// console.log(d.unshift("rishi"));

// console.log(d);


// ///string methods in java script

str="rishi prasad maurya from allahabad allahabad";

// console.log(str.length)
// 44

// console.log(str.indexOf("prasad"));
// 6

// console.log(str.lastIndexOf("allahabad"));
// 35

// console.log(str.replace("rishi", "harry"));
// harry prasad maurya from allahabad allahabad

// console.log(str.slice(0,44));
// rishi prasad maurya from allahabad allahabad


/////my date
/*
mydate=new Date();
// console.log(mydate)

console.log(mydate.getFullYear());
console.log(mydate.getMonth());
console.log(mydate.getDate());
console.log(mydate.getDay());
console.log(mydate.getTime());
console.log(mydate.getHours());
console.log(mydate.getMinutes());
console.log(mydate.getSeconds());
console.log(mydate.getMilliseconds());
console.log(mydate.getTimezoneOffset());
console.log(mydate.getUTCSeconds());

*/
